owner: SwiftFiddle
repo: status.swiftfiddle.com

sites:
  - name: swiftfiddle.com
    url: https://swiftfiddle.com/
  - name: swiftfiddle.com/lang-server
    url: https://swiftfiddle.com/lang-server/health
  - name: swiftfiddle.com/runner/nightly-main
    method: POST
    url: https://swiftfiddle.com/runner/nightly-main/run
    headers:
      - "Content-Type: application/json"
    body: '{ "code": "func hello() { print(\"Hello World!!\") }\nhello()", "_color": true }'
  - name: swiftfiddle.com/runner/5.8
    method: POST
    url: https://swiftfiddle.com/runner/5.8/run
    headers:
      - "Content-Type: application/json"
    body: '{ "code": "func hello() { print(\"Hello World!!\") }\nhello()", "_color": true }'
  - name: swiftfiddle.com/runner/5.7
    method: POST
    url: https://swiftfiddle.com/runner/5.7.3/run
    headers:
      - "Content-Type: application/json"
    body: '{ "code": "func hello() { print(\"Hello World!!\") }\nhello()", "_color": true }'
  - name: swiftfiddle.com/runner/5.6
    method: POST
    url: https://swiftfiddle.com/runner/5.6.3/run
    headers:
      - "Content-Type: application/json"
    body: '{ "code": "func hello() { print(\"Hello World!!\") }\nhello()", "_color": true }'
  - name: swiftfiddle.com/runner/5.5
    method: POST
    url: https://swiftfiddle.com/runner/5.5.3/run
    headers:
      - "Content-Type: application/json"
    body: '{ "code": "func hello() { print(\"Hello World!!\") }\nhello()", "_color": true }'
  - name: swiftfiddle.com/runner/5.4
    method: POST
    url: https://swiftfiddle.com/runner/5.4.3/run
    headers:
      - "Content-Type: application/json"
    body: '{ "code": "func hello() { print(\"Hello World!!\") }\nhello()", "_color": true }'
  - name: swiftfiddle.com/runner/4.2
    method: POST
    url: https://swiftfiddle.com/runner/4.2.4/run
    headers:
      - "Content-Type: application/json"
    body: '{ "code": "func hello() { print(\"Hello World!!\") }\nhello()", "_color": true }'
  - name: power-assert.swiftfiddle.com
    url: https://power-assert.swiftfiddle.com/

status-website:
  cname: status.swiftfiddle.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SwiftFiddle Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "*/20 * * * *"
