owner: SwiftFiddle
repo: status.swiftfiddle.com

sites:
  - name: swiftfiddle.com
    url: https://swiftfiddle.com/
  - name: runner.swift-playground.com
    url: https://runner.swift-playground.com/
  - name: lsp.swift-playground.com
    url: https://lsp.swift-playground.com/

status-website:
  cname: status.swiftfiddle.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SwiftFiddle Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "*/20 * * * *"
